<!DOCTYPE html>
<html>
	<head>
		<link rel='stylesheet' href='css/style.css' type='text/css' />
	</head>
<body>
<div id='welcome'>
	<h1>Welcome to <span id="zf-name">Hell!</span></h1>
	<h3>This is Zend Framework <?php echo $this->zendVersion; ?>, get certified!</h3>

				<div id="more-information">
								<p><img src="https://my.phpcloud.com/images/applogos/empty-zf-logo.png" /></p>
								<p>
												Helpful Links: <br />
												<a href="http://framework.zend.com/">Zend Framework Website</a> |
												<a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
								</p>
				</div>
</div>
</body>
</html>